/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import backend.UserManager;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aaminah1
 */
public class SignupScreen extends javax.swing.JFrame {

    /**
     * Creates new form signupScreen
     */
    public SignupScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        passwordTextField = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        signupButton = new javax.swing.JButton();
        lastNameTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        numberTextField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        firstNameTextField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        usernameTextField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        exit = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        emailTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        showPasswordButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(234, 221, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rsz_logo-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(78, 78, 78))
        );

        jPanel3.setBackground(new java.awt.Color(103, 80, 164));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordTextField.setBackground(new java.awt.Color(103, 80, 164));
        passwordTextField.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        passwordTextField.setForeground(new java.awt.Color(255, 255, 255));
        passwordTextField.setText("Password");
        passwordTextField.setBorder(null);
        passwordTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordTextFieldMouseClicked(evt);
            }
        });
        jPanel3.add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 140, 30));

        jSeparator1.setBackground(new java.awt.Color(33, 0, 93));
        jSeparator1.setForeground(new java.awt.Color(33, 0, 93));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 160, 10));

        jSeparator3.setBackground(new java.awt.Color(33, 0, 93));
        jSeparator3.setForeground(new java.awt.Color(33, 0, 93));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 160, 40));

        signupButton.setBackground(new java.awt.Color(33, 0, 93));
        signupButton.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        signupButton.setForeground(new java.awt.Color(255, 255, 255));
        signupButton.setText("SIGNUP");
        signupButton.setBorder(null);
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        jPanel3.add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 160, 30));

        lastNameTextField.setBackground(new java.awt.Color(103, 80, 164));
        lastNameTextField.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        lastNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        lastNameTextField.setText("last name...");
        lastNameTextField.setBorder(null);
        lastNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastNameTextFieldMouseClicked(evt);
            }
        });
        jPanel3.add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 185, 30));

        jSeparator2.setBackground(new java.awt.Color(33, 0, 93));
        jSeparator2.setForeground(new java.awt.Color(33, 0, 93));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 160, 10));

        numberTextField.setBackground(new java.awt.Color(103, 80, 164));
        numberTextField.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        numberTextField.setForeground(new java.awt.Color(255, 255, 255));
        numberTextField.setText("number...");
        numberTextField.setBorder(null);
        numberTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numberTextFieldMouseClicked(evt);
            }
        });
        jPanel3.add(numberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 185, 30));

        jSeparator4.setBackground(new java.awt.Color(33, 0, 93));
        jSeparator4.setForeground(new java.awt.Color(33, 0, 93));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 160, 10));

        firstNameTextField.setBackground(new java.awt.Color(103, 80, 164));
        firstNameTextField.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        firstNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        firstNameTextField.setText("first name...");
        firstNameTextField.setBorder(null);
        firstNameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstNameTextFieldMouseClicked(evt);
            }
        });
        jPanel3.add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 185, 30));

        jSeparator5.setBackground(new java.awt.Color(33, 0, 93));
        jSeparator5.setForeground(new java.awt.Color(33, 0, 93));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 160, 40));

        usernameTextField.setBackground(new java.awt.Color(103, 80, 164));
        usernameTextField.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        usernameTextField.setForeground(new java.awt.Color(255, 255, 255));
        usernameTextField.setText("username...");
        usernameTextField.setBorder(null);
        usernameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameTextFieldMouseClicked(evt);
            }
        });
        jPanel3.add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 185, 30));

        jSeparator6.setBackground(new java.awt.Color(33, 0, 93));
        jSeparator6.setForeground(new java.awt.Color(33, 0, 93));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 10));

        exit.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(234, 221, 255));
        exit.setText("x");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        jPanel3.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 17, -1));

        jSeparator7.setBackground(new java.awt.Color(33, 0, 93));
        jSeparator7.setForeground(new java.awt.Color(33, 0, 93));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 160, 10));

        emailTextField1.setBackground(new java.awt.Color(103, 80, 164));
        emailTextField1.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        emailTextField1.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField1.setText("email...");
        emailTextField1.setBorder(null);
        emailTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailTextField1MouseClicked(evt);
            }
        });
        jPanel3.add(emailTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 185, 30));

        jLabel1.setFont(new java.awt.Font("Arima Madurai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGNUP ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        showPasswordButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.png"))); // NOI18N
        showPasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showPasswordButtonMouseClicked(evt);
            }
        });
        jPanel3.add(showPasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 50, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        // TODO add your handling code here:
        String lastName = lastNameTextField.getText();
        String firstName = firstNameTextField.getText();
        String email = emailTextField1.getText();
        String number = numberTextField.getText();
        String username = usernameTextField.getText();
        String password = String.valueOf(passwordTextField.getPassword());
        
        try {
            UserManager.addUser(firstName, lastName, email, number, username, password);
            LoginScreen.user = username;
            JOptionPane.showMessageDialog(null, "SIGNUP SUCCESSFUL", "SIGNUP", JOptionPane.INFORMATION_MESSAGE);
            MainScreen mnSc = new MainScreen();
            mnSc.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(SignupScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_signupButtonActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void firstNameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstNameTextFieldMouseClicked
        // TODO add your handling code here:
        firstNameTextField.setText("");

    }//GEN-LAST:event_firstNameTextFieldMouseClicked

    private void lastNameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastNameTextFieldMouseClicked
        // TODO add your handling code here:
        lastNameTextField.setText("");

    }//GEN-LAST:event_lastNameTextFieldMouseClicked

    private void emailTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextField1MouseClicked
        // TODO add your handling code here:
        emailTextField1.setText("");

    }//GEN-LAST:event_emailTextField1MouseClicked

    private void numberTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numberTextFieldMouseClicked
        // TODO add your handling code here:
        numberTextField.setText("");

    }//GEN-LAST:event_numberTextFieldMouseClicked

    private void usernameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTextFieldMouseClicked
        // TODO add your handling code here:
        usernameTextField.setText("");

    }//GEN-LAST:event_usernameTextFieldMouseClicked

    private void passwordTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTextFieldMouseClicked
        // TODO add your handling code here:
        passwordTextField.setText("");

    }//GEN-LAST:event_passwordTextFieldMouseClicked

    private void showPasswordButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPasswordButtonMouseClicked
        // TODO add your handling code here:
        passwordTextField.setEchoChar((char)0);
        
    }//GEN-LAST:event_showPasswordButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void signUpScreen(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JLabel exit;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel showPasswordButton;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
